//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka
{
    using Biblioteka.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaEntities : DbContext
    {
        public BibliotekaEntities()
            : base("name=BibliotekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autori> Autori { get; set; }
        public virtual DbSet<Clanovi> Clanovi { get; set; }
        public virtual DbSet<IzdanjaKnjiga> IzdanjaKnjiga { get; set; }
        public virtual DbSet<IzdavackeKuce> IzdavackeKuce { get; set; }
        public virtual DbSet<Kategorije> Kategorije { get; set; }
        public virtual DbSet<Knjige> Knjige { get; set; }
        public virtual DbSet<Pozajmice> Pozajmice { get; set; }
        public virtual DbSet<PrimjerciKnjiga> PrimjerciKnjiga { get; set; }
    }
}
