//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzdanjaKnjiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IzdanjaKnjiga()
        {
            this.PrimjerciKnjiga = new HashSet<PrimjerciKnjiga>();
        }
    
        public int Id { get; set; }
        public int KnjigeId { get; set; }
        public int IzdavackaKucaId { get; set; }
        public string SlikaKorica { get; set; }
        public int Godina { get; set; }
        public int BrojNaStanju { get; set; }
        public int BrojIzdatih { get; set; }
    
        public virtual IzdavackeKuce IzdavackeKuce { get; set; }
        public virtual Knjige Knjige { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimjerciKnjiga> PrimjerciKnjiga { get; set; }
    }
}
