//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjige
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knjige()
        {
            this.IzdanjeKnjige = new HashSet<IzdanjeKnjige>();
        }
    
        public int KnjigaID { get; set; }
        public string Naslov { get; set; }
        public int AutorID { get; set; }
        public int Godina { get; set; }
        public int KategorijaID { get; set; }
    
        public virtual Autor Autor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzdanjeKnjige> IzdanjeKnjige { get; set; }
        public virtual Kategorija Kategorija { get; set; }
    }
}
