//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozajmice
    {
        public int Id { get; set; }
        public string BibliotekarId { get; set; }
        public int ClanId { get; set; }
        public int PrimjerakKnjigeId { get; set; }
        public System.DateTime DatumPozajmice { get; set; }
        public System.DateTime DatumZakazanogVracanja { get; set; }
        public Nullable<System.DateTime> DatumVracanja { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual PrimjerciKnjiga PrimjerciKnjiga { get; set; }
    }
}
