//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteka.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimjerciKnjiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrimjerciKnjiga()
        {
            this.Pozajmice = new HashSet<Pozajmice>();
        }
    
        public int Id { get; set; }
        public string Sifra { get; set; }
        public int IzdanjeKnjigeId { get; set; }
        public bool Zaduzen { get; set; }
    
        public virtual IzdanjaKnjiga IzdanjaKnjiga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pozajmice> Pozajmice { get; set; }
    }
}
